import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { ReactLenis } from 'lenis/react';

const zentry = localFont({
  variable: '--font-zentry',
  src: '../public/fonts/zentry-regular.woff2',
});

const circularwebBook = localFont({
  variable: '--font-circularweb-book',
  src: '../public/fonts/circularweb-book.woff2',
});

const general = localFont({
  variable: '--font-general',
  src: '../public/fonts/general.woff2',
});

const robert = localFont({
  variable: '--font-robert',
  src: [
    {
      path: '../public/fonts/robert-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/robert-medium.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${zentry.variable} ${circularwebBook.variable} ${robert.variable} ${general.variable} h-full antialiased`}
    >
      <body className="w-dvw overflow-x-hidden font-general bg-[#dfdff0]">
        <ReactLenis root options={{ lerp: 0.05 }}>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
